name: SPDX

on:
  push:
    branches:
      - siva_arm

permissions:
  contents: write

jobs:
  compare-spdx:
    runs-on: zephyr-specific
    permissions:
      contents: write # to create GitHub release entry

      
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0


# Get the spdx file from release v4.2.0 to use in Run SPDX CompareDocs

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/heads/}"
          echo "TRIMMED_VERSION=${GITHUB_REF#refs/heads/}"
          echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "TRIMMED_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Check runner RAM
        run: |
          echo "Memory info:"
          free -h || vm_stat || top -l 1 | grep PhysMem || echo "Command not found"

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5.0.0
        with:
          args: spdx -o zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      - name: upload-results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        continue-on-error: true
        with:
          name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
          path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

          
# mychanges
      # - name: Download old SPDX from Release v4.2.0
      #   run: |
      #     mkdir old_spdx
      #     cd old_spdx
      #     gh release download v4.2.0-rc2 --pattern "zephyr-v4.2.0.spdx"
      #     pwd
      #     ls -al
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Download SPDX from latest Release
        run: |
          # mkdir -p old_spdx
          # cd old_spdx
          ls -al

          # Get latest release tag name
          latest_release_tag=$(gh release view --json tagName --jq .tagName)

          echo "Latest release is: $latest_release_tag"

          # Download SPDX file from latest release
          gh release download "$latest_release_tag" --pattern "*.spdx"

          pwd
          ls -al
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload old spdx
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-v4.2.0.spdx
          path: zephyr-v4.2.0.spdx


      # - name: Upload/replace SPDX if file already exists
      #   run: |
      #     if [ -f zephyr-${{ steps.get_version.outputs.VERSION }}.spdx ]; then
      #       echo "File exists. Uploading..."
      #       gh api \
      #         -X POST \
      #         -H "Accept: application/vnd.github+json" \
      #         /repos/${{ github.repository }}/actions/artifacts \
      #         -F name="zephyr-${{ steps.get_version.outputs.VERSION }}" \
      #         -F file=@zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
      #     else
      #       echo "No SPDX file to upload."
      #     fi
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Upload spdx
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
      #     path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Download SPDX Tools
        run: |
          pwd
          curl -LO https://github.com/spdx/tools-java/releases/download/v2.0.0/tools-java-2.0.0.zip
          unzip tools-java-2.0.0.zip

      # - name: Run SPDX CompareDocs
      #   run: |
      #     pwd
      #     ls -al
      #     ls -al tools-java-2.0.0-jar-with-dependencies.jar
      #     java -jar tools-java-2.0.0-jar-with-dependencies.jar \
      #       CompareDocs spdx_compare_out.xlsx zephyr-${{ steps.get_version.outputs.VERSION }}.spdx zephyr-v4.2.0.spdx 
      #     java -Xmx2G -jar tools-java-2.0.0-jar-with-dependencies.jar \
      #       CompareDocs spdx_compare_out.xlsx zephyr-${{ steps.get_version.outputs.VERSION }}.spdx zephyr-v4.2.0.spdx


      - name: Run SPDX CompareDocs
        run: |
          pwd
          ls -al
          ls -al tools-java-2.0.0-jar-with-dependencies.jar
          java -Xmx4G -jar tools-java-2.0.0-jar-with-dependencies.jar \
            CompareDocs spdx_compare_out.xlsx zephyr-${{ steps.get_version.outputs.VERSION }}.spdx zephyr-v4.2.0.spdx

            
      - name: Upload comparison result
        uses: actions/upload-artifact@v4
        with:
          name: spdx-comparison-output
          path: tests/sample_spdx/spdx_compare_out.xlsx


