name: SPDX

on:
  push:
    branches:
      - siva_arm

permissions:
  contents: write

jobs:
  compare-spdx:
    runs-on: zephyr-specific
    permissions:
      contents: write # to create GitHub release entry

    defaults:
      run:
        working-directory: tests/sample_spdx

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  

      - name: Download SPDX Tools
        run: |
          curl -LO https://github.com/spdx/tools-java/releases/download/v2.0.0/tools-java-2.0.0.zip
          unzip tools-java-2.0.0.zip

      - name: Run SPDX CompareDocs
        run: |
          pwd
          ls -al
          ls -al tools-java-2.0.0-jar-with-dependencies.jar
          java -jar tools-java-2.0.0-jar-with-dependencies.jar \
            CompareDocs spdx_compare_out.xlsx zephyr.spdx zephyr2.spdx

      - name: Upload comparison result
        uses: actions/upload-artifact@v4
        with:
          name: spdx-comparison-output
          path: tests/sample_spdx/spdx_compare_out.xlsx

      # - name: test
      #   run: |
      #     pwd
      #     ls -al
      #     chmod +x setup_spdx_zephyr.sh
      #     ./setup_spdx_zephyr.sh