name: Create a Release

on:
  push:
    branches:
      - siva_arm

permissions:
  contents: write

jobs:
  compare-spdx:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # to create GitHub release entry
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0



# Get the spdx file from release v4.1.0 to use in Run SPDX CompareDocs

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/heads/}"
          echo "TRIMMED_VERSION=${GITHUB_REF#refs/heads/}"
          echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "TRIMMED_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5.0.0
        with:
          args: spdx -o zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      - name: upload-results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        continue-on-error: true
        with:
          name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
          path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

# mychanges
      - name: Download old SPDX from Release v4.1.0
        run: |
          mkdir old_spdx
          cd old_spdx
          gh release download v4.1.0-rc2 --pattern "zephyr-v4.1.0.spdx"
          pwd
          ls -al
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload spdx
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-v4.1.0.spdx
          path: old_spdx/zephyr-v4.1.0.spdx

      # - name: Upload spdx
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
      #     path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      # - name: Set up Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'  

      # - name: Download SPDX Tools
      #   run: |
      #     curl -LO https://github.com/spdx/tools-java/releases/download/v2.0.0/tools-java-2.0.0.zip
      #     unzip tools-java-2.0.0.zip

      # - name: Run SPDX CompareDocs
      #   run: |
      #     pwd
      #     ls -al
      #     ls -al tools-java-2.0.0-jar-with-dependencies.jar
      #     java -jar tools-java-2.0.0-jar-with-dependencies.jar \
      #       CompareDocs spdx_compare_out.xlsx zephyr-${{ steps.get_version.outputs.VERSION }}.spdx zephyr-<release v4.1.0>.spdx 

      # - name: Upload comparison result
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: spdx-comparison-output
      #     path: tests/sample_spdx/spdx_compare_out.xlsx


